version: '2.3'
services:
  notebook:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/
    entrypoint: jupyter notebook --NotebookApp.token='' --allow-root